// Exact fixed-A batched candidate generator for up to 64 B records.
// It shares every cap-prefix traversal across all currently compatible B queries.
#include <algorithm>
#include <array>
#include <bit>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <fstream>
#include <iostream>
#include <numeric>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>
__extension__ typedef unsigned __int128 U128;
constexpr int N=11,P=121; constexpr U128 FULL=(U128(1)<<P)-1;
static int pc(U128 x){return std::popcount((uint64_t)x)+std::popcount((uint64_t)(x>>64));}
static int least(U128 x){uint64_t a=(uint64_t)x;return a?std::countr_zero(a):64+std::countr_zero((uint64_t)(x>>64));}
static U128 ph(const std::string&s){if(s.size()!=31)throw std::runtime_error("mask width");U128 x=0;for(char c:s){x<<=4;if(c>='0'&&c<='9')x|=c-'0';else if(c>='a'&&c<='f')x|=c-'a'+10;else throw std::runtime_error("mask hex");}if(x>>121)throw std::runtime_error("high bits");return x;}
static std::string hx(U128 x){static const char*d="0123456789abcdef";std::string s(31,'0');for(int i=30;i>=0;--i){s[i]=d[(unsigned)(x&15)];x>>=4;}return s;}
struct Line{U128 mask=0;};
struct RowOption{U128 mask=0;std::array<U128,P> block{};uint8_t c1=0,c2=0,n=0;};
struct Cand{U128 mask=0;uint16_t sr=0,sc=0;};
struct BRec{U128 b=0,res=0;std::string id;uint8_t sr=0,sc=0;std::vector<std::pair<U128,uint8_t>> critical;};
static std::vector<std::string> tab(const std::string&s){std::vector<std::string>v;size_t a=0;for(;;){size_t b=s.find('\t',a);v.push_back(s.substr(a,b==std::string::npos?b:b-a));if(b==std::string::npos)break;a=b+1;}return v;}
static std::vector<Line> geometry(){std::vector<Line>v;for(int dc=0;dc<N;++dc)for(int dr=-(N-1);dr<N;++dr){if(dc==0){if(dr!=1)continue;}else if(std::gcd(dc,std::abs(dr))!=1)continue;for(int r=0;r<N;++r)for(int c=0;c<N;++c){if(0<=r-dr&&r-dr<N&&0<=c-dc&&c-dc<N)continue;U128 m=0;for(int rr=r,cc=c;0<=rr&&rr<N&&0<=cc&&cc<N;rr+=dr,cc+=dc)m|=U128(1)<<(rr*N+cc);if(pc(m)>=3)v.push_back({m});}}std::sort(v.begin(),v.end(),[](auto&a,auto&b){return a.mask<b.mask;});v.erase(std::unique(v.begin(),v.end(),[](auto&a,auto&b){return a.mask==b.mask;}),v.end());if(v.size()!=628)throw std::runtime_error("geometry");return v;}
static std::pair<uint16_t,uint16_t> singles(U128 m,int deficit){uint16_t rs=0,cs=0;for(int r=0;r<N;++r){int z=0;for(int c=0;c<N;++c)z+=(m>>(r*N+c))&1;if(z==1)rs|=uint16_t(1)<<r;else if(z!=2)throw std::runtime_error("row profile");}for(int c=0;c<N;++c){int z=0;for(int r=0;r<N;++r)z+=(m>>(r*N+c))&1;if(z==1)cs|=uint16_t(1)<<c;else if(z!=2)throw std::runtime_error("col profile");}if(std::popcount(rs)!=deficit||std::popcount(cs)!=deficit)throw std::runtime_error("singleton deficit");return {rs,cs};}
static std::pair<U128,std::vector<BRec>> load(const std::string&path,size_t begin,size_t end){std::ifstream f(path);if(!f)throw std::runtime_error("open");std::string line;if(!std::getline(f,line))throw std::runtime_error("empty");auto h=tab(line);bool hist=h[0]=="rank";std::vector<BRec>all;U128 A=0;bool have=false;auto add=[&](auto&x){BRec r;U128 a;if(hist){if(x.size()<8)throw std::runtime_error("fields");r.id="fixedA-rank"+std::string(5-x[0].size(),'0')+x[0];r.b=ph(x[6]);r.res=ph(x[7]);a=FULL^r.b^r.res;}else{if(x.size()!=4)throw std::runtime_error("fields");a=ph(x[0]);r.b=ph(x[1]);r.res=ph(x[2]);r.id=x[3];}if(!have)A=a,have=true;else if(a!=A)throw std::runtime_error("A mismatch");all.push_back(std::move(r));};if(!hist)add(h);while(std::getline(f,line)){if(!line.empty()){auto x=tab(line);add(x);}}if(end==(size_t)-1||end>all.size())end=all.size();if(begin>=end||end-begin>64)throw std::runtime_error("range must contain 1..64 rows");return {A,std::vector<BRec>(all.begin()+begin,all.begin()+end)};}
class Batch{
public:
 Batch(U128 a,std::vector<BRec> b,std::string dump,uint64_t lim,double secs,int critical_row,bool independent_mode,bool exact_columns):A(a),B(std::move(b)),dumpdir(std::move(dump)),node_limit(lim),sec_limit(secs),critical_start(critical_row),independent(independent_mode),exact_column_filter(exact_columns),L(geometry()){prepare();}
 int run(){started=std::chrono::steady_clock::now();uint64_t all=B.size()==64?~uint64_t(0):(uint64_t(1)<<B.size())-1;if(independent){for(size_t i=0;i<B.size()&&!limited;++i)enumerate(uint64_t(1)<<i);}else enumerate(all);
  double sec=elapsed();if(!limited){for(auto&v:out)std::sort(v.begin(),v.end(),[](auto&a,auto&b){return a.mask<b.mask;});if(!dumpdir.empty())dump();}
  uint64_t occ=0;for(auto&v:out)occ+=v.size();std::cout<<(limited?"INCOMPLETE":"CANDIDATE_BATCH_COMPLETE")<<" records "<<B.size()<<" nodes "<<nodes<<" leaves "<<leaves<<" unique_leaf_caps "<<unique_leaf_caps<<" candidate_occurrences "<<occ<<" empty_prunes "<<empty_prunes<<" capacity_rejects "<<capacity_rejects<<" column_query_prunes "<<column_query_prunes<<" critical_prefix_prunes "<<critical_prefix_prunes<<" seconds "<<sec<<"\n";for(size_t i=0;i<B.size();++i)std::cout<<"RECORD "<<i<<" "<<B[i].id<<" candidates "<<out[i].size()<<"\n";return limited?30:0;}
private:
 void enumerate(uint64_t all){for(int r1=0;r1<N;++r1)if(!((a_sr>>r1)&1))for(int r2=r1+1;r2<N;++r2)if(!((a_sr>>r2)&1)){uint64_t allow=all;for(size_t i=0;i<B.size();++i)if((B[i].sr>>r1&1)||(B[i].sr>>r2&1))allow&=~(uint64_t(1)<<i);if(!allow)continue;single1=r1;single2=r2;coldeg.fill(0);selected_n=0;dfs(0,0,0,allow);if(limited)return;}}
 double elapsed()const{return std::chrono::duration<double>(std::chrono::steady_clock::now()-started).count();}
 bool budget(){if(node_limit&&nodes>=node_limit){limited=true;return false;}if(sec_limit>0&&(nodes&0x3ffff)==0&&elapsed()>=sec_limit){limited=true;return false;}return true;}
 void prepare(){if(pc(A)!=21)throw std::runtime_error("A size");for(auto&l:L)if(pc(A&l.mask)>2)throw std::runtime_error("A cap");auto as=singles(A,1);a_sr=as.first;a_sc=as.second;for(int r=0;r<N;++r)for(int c=0;c<N;++c){int p=r*N+c;rows[r]|=U128(1)<<p;cols[c]|=U128(1)<<p;}for(int i=0;i<N;++i){main_diag|=U128(1)<<(i*N+i);anti_diag|=U128(1)<<(i*N+10-i);}for(int p=0;p<P;++p)for(int q=p+1;q<P;++q){int pr=p/N,pc0=p%N,qr=q/N,qc=q%N;U128 m=0;for(int x=0;x<P;++x){int xr=x/N,xc=x%N;if((qr-pr)*(xc-pc0)==(qc-pc0)*(xr-pr))m|=U128(1)<<x;}pairline[p][q]=pairline[q][p]=m;}
  U128 base=FULL^A;for(int r=0;r<N;++r){U128 m=base&rows[r];std::array<int,N>p{};int n=0;while(m){p[n++]=least(m);m&=m-1;}for(int i=0;i<n;++i){RowOption o;o.mask=U128(1)<<p[i];o.c1=p[i]%N;o.n=1;for(int old=0;old<P;++old)o.block[old]=pairline[p[i]][old];one[r].push_back(std::move(o));}for(int i=0;i<n;++i)for(int j=i+1;j<n;++j){RowOption o;o.mask=(U128(1)<<p[i])|(U128(1)<<p[j]);o.c1=p[i]%N;o.c2=p[j]%N;o.n=2;for(int old=0;old<P;++old)o.block[old]=pairline[p[i]][old]|pairline[p[j]][old];two[r].push_back(std::move(o));}}
  for(int r=N;r>=0;--r){future_all[r]=r==N?0:future_all[r+1]|(base&rows[r]);for(int c=0;c<N;++c)future[r][c]=r==N?0:future[r+1][c]|(base&rows[r]&cols[c]);}
  out.resize(B.size());for(size_t i=0;i<B.size();++i){auto s=singles(B[i].b,1);B[i].sr=s.first;B[i].sc=s.second;if(pc(B[i].b)!=21||B[i].b&A||B[i].res!=(FULL^A^B[i].b))throw std::runtime_error("B record");for(auto&l:L){if(pc(B[i].b&l.mask)>2)throw std::runtime_error("B cap");int z=pc(B[i].res&l.mask);if(z>8)throw std::runtime_error("residual capacity");if(z>6)B[i].critical.push_back({l.mask,uint8_t(z-6)});}}
  for(size_t i=0;i<B.size();++i)for(int r=0;r<=N;++r){future_all_b[i][r]=future_all[r]&~B[i].b;for(int c=0;c<N;++c)future_b[i][r][c]=future[r][c]&~B[i].b;}
  for(int p=0;p<P;++p){uint64_t m=0;for(size_t i=0;i<B.size();++i)if(!((B[i].b>>p)&1))m|=uint64_t(1)<<i;point_clear[p]=m;}
 }
 uint64_t filter_critical_possible(int row,U128 selected,U128 blocked,uint64_t allow){uint64_t keep=0;while(allow){int i=std::countr_zero(allow);allow&=allow-1;bool ok=true;for(auto&cl:B[i].critical){int have=pc(selected&cl.first);if(have>=cl.second)continue;U128 a=future_all_b[i][row]&~blocked&cl.first;int need=cl.second-have;if((need==1&&a==0)||(need==2&&(a==0||(a&(a-1))==0))){ok=false;break;}}if(ok)keep|=uint64_t(1)<<i;else ++critical_prefix_prunes;}return keep;}
 uint64_t filter_basic_col_possible(int row,uint64_t allow){for(int c=0;c<N;++c){int d=coldeg[c];int avail=pc(future[row][c]);if(d>2||d+avail<1)return 0;}return allow;}
 uint64_t filter_col_possible(int row,U128 blocked,uint64_t allow){uint64_t keep=0;while(allow){int i=std::countr_zero(allow);allow&=allow-1;int forced=0,potential=0;bool ok=true;uint16_t fixed=a_sc|B[i].sc;for(int c=0;c<N&&ok;++c){int d=coldeg[c];U128 a=future_b[i][row][c]&~blocked;bool one=a!=0,two=(a&(a-1))!=0;if((fixed>>c)&1){if((d==0&&!two)||(d==1&&!one)||d>2)ok=false;}else{if(d<2)++potential;if(d==0){if(!one)ok=false;else if(!two)++forced;}else if(d==1&&!one)++forced;else if(d>2)ok=false;}}if(ok&&forced<=2&&potential>=2)keep|=uint64_t(1)<<i;else ++column_query_prunes;}return keep;}
 void dfs(int row,U128 selected,U128 blocked,uint64_t allow){if(!budget())return;++nodes;if(!allow){++empty_prunes;return;}allow=exact_column_filter?filter_col_possible(row,blocked,allow):filter_basic_col_possible(row,allow);if(!allow){++empty_prunes;return;}if(row>=critical_start){allow=filter_critical_possible(row,selected,blocked,allow);if(!allow){++empty_prunes;return;}}if(row==N){++leaves;uint16_t sc=0;for(int c=0;c<N;++c){if(coldeg[c]==1)sc|=uint16_t(1)<<c;else if(coldeg[c]!=2)return;}if(std::popcount(sc)!=2||(sc&a_sc)||!(selected&main_diag)||!(selected&anti_diag))return;++unique_leaf_caps;uint16_t sr=(uint16_t(1)<<single1)|(uint16_t(1)<<single2);uint64_t x=allow;while(x){int i=std::countr_zero(x);x&=x-1;if(sc&B[i].sc)continue;bool ok=true;for(auto&cl:B[i].critical)if(pc(selected&cl.first)<cl.second){ok=false;break;}if(!ok){++capacity_rejects;continue;}out[i].push_back({selected,sr,sc});}return;}
  int need=(row==single1||row==single2)?1:2;auto&opts=need==1?one[row]:two[row];for(auto&o:opts){if(o.mask&blocked||coldeg[o.c1]>=2||(o.n==2&&coldeg[o.c2]>=2))continue;uint64_t na=allow;U128 t=o.mask;while(t){int p=least(t);na&=point_clear[p];t&=t-1;}if(!na){++empty_prunes;continue;}U128 nb=blocked;for(int k=0;k<selected_n;++k)nb|=o.block[selected_pts[k]];t=o.mask;while(t){selected_pts[selected_n++]=least(t);t&=t-1;}++coldeg[o.c1];if(o.n==2)++coldeg[o.c2];dfs(row+1,selected|o.mask,nb,na);if(o.n==2)--coldeg[o.c2];--coldeg[o.c1];selected_n-=o.n;if(limited)return;}}
 void dump(){std::string cmd="mkdir -p '"+dumpdir+"'";if(std::system(cmd.c_str())!=0)throw std::runtime_error("mkdir");for(size_t i=0;i<B.size();++i){std::string p=dumpdir+"/"+B[i].id+".tsv.partial";std::ofstream f(p);if(!f)throw std::runtime_error("dump");f<<"mask\tsingleton_rows\tsingleton_cols\n";for(auto&c:out[i])f<<hx(c.mask)<<'\t'<<c.sr<<'\t'<<c.sc<<'\n';f.close();std::string q=dumpdir+"/"+B[i].id+".tsv";if(std::rename(p.c_str(),q.c_str())!=0)throw std::runtime_error("rename");}}
 U128 A=0,main_diag=0,anti_diag=0;std::vector<BRec>B;std::string dumpdir;uint64_t node_limit=0,nodes=0,leaves=0,unique_leaf_caps=0,empty_prunes=0,capacity_rejects=0,column_query_prunes=0,critical_prefix_prunes=0;double sec_limit=0;int critical_start=99;bool independent=false,exact_column_filter=true,limited=false;std::chrono::steady_clock::time_point started;std::vector<Line>L;uint16_t a_sr=0,a_sc=0;std::array<U128,N>rows{},cols{};std::array<std::array<U128,N>,N+1>future{};std::array<U128,N+1>future_all{};std::array<std::array<std::array<U128,N>,N+1>,64>future_b{};std::array<std::array<U128,N+1>,64>future_all_b{};std::array<std::array<U128,P>,P>pairline{};std::array<std::vector<RowOption>,N>one{},two{};std::array<uint64_t,P>point_clear{};std::vector<std::vector<Cand>>out;int single1=0,single2=0,selected_n=0;std::array<int,20>selected_pts{};std::array<int,N>coldeg{};
};
int main(int argc,char**argv){try{std::string branch,dump;size_t begin=0,end=(size_t)-1;uint64_t nodes=0;double seconds=0;int critical_row=99;bool independent=false,exact_columns=true;for(int i=1;i<argc;++i){std::string a=argv[i];auto get=[&](){if(++i>=argc)throw std::runtime_error("missing arg");return std::string(argv[i]);};if(a=="--branch")branch=get();else if(a=="--begin")begin=std::stoull(get());else if(a=="--end")end=std::stoull(get());else if(a=="--dump-dir")dump=get();else if(a=="--node-limit")nodes=std::stoull(get());else if(a=="--seconds")seconds=std::stod(get());else if(a=="--critical-prefix-row")critical_row=std::stoi(get());else if(a=="--independent-control")independent=true;else if(a=="--disable-exact-column-filter")exact_columns=false;else throw std::runtime_error("bad arg "+a);}if(branch.empty())throw std::runtime_error("--branch");auto [A,B]=load(branch,begin,end);return Batch(A,std::move(B),dump,nodes,seconds,critical_row,independent,exact_columns).run();}catch(std::exception&e){std::cerr<<"ERROR "<<e.what()<<"\n";return 2;}}
